name: Deploy KOUBA

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to server
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restart containers
        run: docker compose up -d --remove-orphans

      - name: Clean up unused images
        run: docker image prune -f
